### PR TITLE
Feature/joined gsa

### PR DESCRIPTION
**Pull request by afaulconbridge**
Combine the existing Illumina Global Screening Array implementations together, and make them more adaptable for other variations in future.

### CODE REVIEW

**Review by willgdjones — APPROVED** [review]

**Review by willgdjones — APPROVED** [review]

**Comment by afaulconbridge** [comment]
This appears to be causing a significant performance degradation on AWS Lambda via sano develop (~18s -> ~180s). I'm not going to merge this branch in until I understand that some more.

**Comment by willgdjones** [comment]
Ok 👍

**Review by willgdjones — APPROVED** [review]

**Comment by afaulconbridge** [comment]
@willgdjones I've made significant changes to this, so another review would be good before I merge it.

**Comment by willgdjones** [comment]
ok 👍

**Review by willgdjones — APPROVED** [review]

**Pull request merged**
